# This is a generated file. Not intended for manual editing.
services:
  langup:
    build:
      context: "/Users/gauthierseyzeriat/repos/LangUp"
      dockerfile: "LangUp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/LangUp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "langup:dev"
    ports: []
    volumes:
    - "/Users/gauthierseyzeriat/repos/LangUp/LangUp:/app:rw"
    - "/Users/gauthierseyzeriat/repos/LangUp:/src:rw"
    - "/Users/gauthierseyzeriat/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
